name: "ci-workflow"

on: 
  push: 
    branches:
      - develop

  pull_request:
    branches:
      - develop
    
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Step
        run: echo "Welcome To Github Actions"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Repository Basic Info"
        run: |
          echo "Repository Name: ${{ github.repository }}" 
          echo "Repository Owner: ${{ github.owner }}" 
